### PR TITLE
[mrg] add environment.yml 

### LINKED ISSUE #5: thoughts for future workflow improvements
in #4 , @raynamharris suggested an improvement

>would be nice to have some output when the .py scripts are running if they take a while...

and I wanted to follow up -

there are two changes that could be made,

1. add an argparse argument parser that specifies a default `-o/--output` 
2. and/or use `print(..., file=sys.stderr)` to output progress messages

### LINKED ISSUE #7: add an environment.yml?
and use pip to install deriva per [this link](https://stackoverflow.com/questions/35245401/combining-conda-environment-yml-with-pip-requirements-txt)

### PR DESCRIPTION
**Pull request by raynamharris**
adds a yml file that works to install the software with and close #7 and #5 

```
conda env create -f binder/environment.yml
```

Note: I saved it in a repo called **binder** because I was hoping to use it to run the program in a browser, but the run_C2M2_script is failing. 

To test:
1. Click [Binder](https://mybinder.org/v2/gh/nih-cfde/c2m2_cv_usage/add_yml_binder)
1. Open a terminal
1. Run `conda activate deriva`
1. Run `make`

This fixes #7!

### CODE REVIEW

**Comment by ctb** [comment]
note that you don't need the `postBuild` script specifically; binder will detect either `environment.yml` or `binder/environment.yml`.

**Comment by raynamharris** [comment]
nice! i like using the postBuild to activate the enviornment. ill move the files out of the sub-dir

**Comment by ctb** [comment]
> nice! i like using the postBuild to activate the enviornment. ill move the files out of the sub-dir

ok - note that the current `postBuild` file is creating the environment (which is not needed) and not activating it. So as of 41269980fcf I don't think it's doing anything.

**Comment by raynamharris** [comment]
okay, yml file works great to install requrirments so I'm gonna call this good. will worry about binder later.

**Comment by ctb** [comment]
(the binder fails because the `c2m2_cv_usage.py` script fails with out of memory)

**Review by ctb — APPROVED** [review]

**Pull request merged**
